"use client";
import { useState } from "react";
import Image from "next/image";
import { ActionForm, Table, permitted, text, type Row, type Run, type Session, type Snapshot } from "./ui";

export default function ModulePanels({ panel, snapshot: s, auth, run, busy, message, expired }: { panel: string; snapshot: Snapshot; auth: Session; run: Run; busy: boolean; message: (text: string) => void; expired: () => void }) {
  const owner = auth.actor?.role === "owner", can = (permission: Parameters<typeof permitted>[1]) => permitted(auth.actor, permission);
  const [analytics, setAnalytics] = useState<{ rows: Row[]; note: string; coverage: Row }>();
  const [preview, setPreview] = useState<Row[]>(), [viewerQuery, setViewerQuery] = useState("");
  if (panel === "Connections" && owner) return <>
    <section><h2>Kick connection</h2><pre>{JSON.stringify(s.kick, null, 2)}</pre><div className="actions"><button disabled={busy} onClick={async () => { try { const response = await fetch("/api/connections/kick?moderation=1", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": auth.csrf ?? "" }, body: "{}" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); location.assign(result.url); } catch (error) { message(error instanceof Error ? error.message : "Authorization failed"); } }}>Authorize Kick with moderation</button>{["refresh", "subscribe", "disconnect"].map(action => <button className="secondary" disabled={busy} key={action} onClick={() => run(`kick.${action}`)}>{action}</button>)}</div></section>
    {(["kick", "discord", "youtube"] as const).map(provider => <form key={provider} onSubmit={async event => { event.preventDefault(); const data: Row = Object.fromEntries(new FormData(event.currentTarget)); if (provider === "kick") data.broadcasterId = Number(data.broadcasterId); const form = event.currentTarget; await run("integration.save", { provider, data }); form.reset(); }}><h2>{provider} application settings</h2><p className="help">Encrypted on the host and never returned. Fixture mode rejects live credentials.</p><div className="fields">{(provider === "kick" ? ["clientId", "clientSecret", "broadcasterId"] : provider === "discord" ? ["applicationId", "publicKey", "botToken"] : ["key"]).map(key => <label key={key}>{key}<input name={key} type={/secret|token|key/i.test(key) ? "password" : "text"} autoComplete="off" required /></label>)}</div><button disabled={busy}>Save {provider} settings</button></form>)}<button disabled={busy} onClick={() => run("discord.register")}>Register Discord commands in allowed guilds</button>
  </>;
  if (panel === "Timers") return can("operate") && <div className="actions"><button onClick={() => run("timers.pause")}>Pause all timers</button><button onClick={() => run("timers.resume")}>Resume timers</button><p>Offline and paused timers reschedule without sending missed messages.</p></div>;
  if (panel === "Alerts") return <>
    {can("operate") && <><ActionForm action="alert.manual" fields={["reason"]} button="Send manual alert" run={run} busy={busy} /><label>Preview event<select id="preview-event">{["channel.followed", "channel.subscription.new", "channel.subscription.renewal", "channel.subscription.gifts", "manual", "goal", "media"].map(event => <option key={event}>{event}</option>)}</select></label><button className="secondary" onClick={async () => { const event = (document.getElementById("preview-event") as HTMLSelectElement).value; const response = await fetch("/api/control", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": auth.csrf ?? "" }, body: JSON.stringify({ action: "alert.preview", input: { event } }) }); const result = await response.json(); if (response.ok) setPreview(result.alerts); else message(result.error); }}>Preview without delivery</button>{preview && <div className="widget-root" data-theme="mint" data-motion="true" aria-label="Alert preview">{preview.length ? preview.map((alert, index) => <article key={index}>{Boolean(alert.image) && <Image unoptimized src={`/api/assets/${encodeURIComponent(String(alert.image))}`} width={640} height={360} alt="" />}<h2>{text(alert.text)}</h2>{Boolean(alert.sound) && <audio controls src={`/api/assets/${encodeURIComponent(String(alert.sound))}`} />}</article>) : <p>No enabled alert configuration for this event.</p>}</div>}</>}
    {owner && <form onSubmit={async event => { event.preventDefault(); const file = (event.currentTarget.elements.namedItem("asset") as HTMLInputElement).files?.[0]; if (!file) return; if (file.size > 8 * 1024 * 1024) { message("Assets must be at most 8 MiB."); return; } const reader = new FileReader(); reader.onload = () => void run("asset.upload", { name: file.name, base64: String(reader.result).split(",")[1] }); reader.readAsDataURL(file); }}><h3>Upload image or sound</h3><label>Asset file<input type="file" name="asset" accept="image/png,image/jpeg,image/gif,image/webp,audio/mpeg,audio/ogg,audio/wav" required /></label><button disabled={busy}>Upload</button><Table rows={s.assets ?? []} columns={["id", "name", "format", "bytes"]} />{s.assets?.map(asset => <button key={String(asset.id)} type="button" className="secondary" onClick={() => run("asset.delete", { id: asset.id })}>Delete {text(asset.name)}</button>)}</form>}
  </>;
  if (panel === "Media") return <>
    <p>Enable media in Maintenance settings. Live playback needs a visible OBS player source and its separate credential.</p>{can("media") && <ActionForm action="media.request" fields={["url"]} button="Add YouTube request" run={run} busy={busy} />}
    <section><h2>Player · {s.player.state}</h2><p>{s.player.error ?? "Ready for an approved item and connected player."}</p><p>Version {s.player.version} · Volume {s.player.volume}%</p>{can("media") && <div className="actions">{["pause", "resume", "skip"].map(action => <button key={action} onClick={() => run(`player.${action}`, { version: s.player.version })}>{action}</button>)}<label>Volume<input type="range" min={0} max={100} defaultValue={s.player.volume} onPointerUp={event => run("player.volume", { version: s.player.version, value: Number(event.currentTarget.value) })} onKeyUp={event => { if (["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) void run("player.volume", { version: s.player.version, value: Number(event.currentTarget.value) }); }} /></label></div>}</section>
    <section><h2>Requests and queue</h2>{s.media.map(item => <article key={String(item.id)}><h3>{text(item.title ?? item.video_id)}</h3><p>{text(item.status)} · {text(item.duration ?? "Unknown")} seconds · {text(item.error ?? "")}</p><p className="help">{text(item.id)} · version {text(item.version)}</p>{can("media") && <div className="actions">{(item.status === "pending" ? ["approve", "reject", "remove"] : ["approved", "failed"].includes(String(item.status)) ? ["remove"] : []).map(action => <button key={action} onClick={() => run(`media.${action}`, { target: item.id, version: item.version })}>{action}</button>)}{item.status === "approved" && <button className="secondary" onClick={() => run("media.reorder", { ids: [item.id, ...s.media.filter(row => row.status === "approved" && row.id !== item.id).map(row => row.id)] })}>Move to top</button>}</div>}</article>)}{can("media") && <button className="secondary" onClick={() => { if (confirm("Remove waiting queue items?")) void run("media.clear"); }}>Clear waiting items</button>}</section>
  </>;
  if (panel === "Moderation") return <>
    {can("moderate") && <><div className="actions"><button onClick={() => run("moderation.pause")}>Emergency pause moderation</button><button onClick={() => run("moderation.resume")}>Resume moderation</button></div><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void run("moderation.bulk", { operation: form.get("operation"), targets: String(form.get("targets")).split(/[\s,]+/).filter(Boolean).map(Number), reason: form.get("reason"), acknowledge: form.get("acknowledge") === "on" }); }}><h3>Reviewed bulk moderation (up to 20 viewers)</h3><label>Viewer IDs<textarea name="targets" required /></label><label>Action<select name="operation"><option>warn</option><option>timeout</option><option>ban</option></select></label><label>Reason<input name="reason" required /></label><label>I have reviewed every target<input name="acknowledge" type="checkbox" required /></label><button>Queue reviewed actions</button></form></>}
    {can("moderate") && <><ActionForm action="moderation.warn" fields={["target", "reason"]} button="Warn viewer" run={run} busy={busy} /><ActionForm action="moderation.timeout" fields={["target", "value", "reason"]} button="Timeout viewer (minutes)" run={run} busy={busy} /><ActionForm action="moderation.ban" fields={["target", "reason", "acknowledge"]} button="Ban viewer" run={run} busy={busy} /><ActionForm action="moderation.delete" fields={["target", "message", "reason", "acknowledge"]} button="Delete message" run={run} busy={busy} />
      <form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget), rule = s.documents.find(d => d.id === form.get("rule")); if (rule) void run("moderation.test", { rule: rule.data, content: form.get("content"), role: form.get("role") }); }}><h3>Safe rule test</h3><label>Rule<select name="rule">{s.documents.filter(d => d.kind === "rule").map(d => <option value={d.id} key={d.id}>{String(d.data.name)}</option>)}</select></label><label>Sample message<input name="content" required /></label><label>Viewer role<select name="role">{["viewer", "subscriber", "vip", "moderator", "broadcaster"].map(role => <option key={role}>{role}</option>)}</select></label><button>Evaluate without effects</button></form></>}
    <section><h2>Incidents</h2><Table rows={s.incidents} columns={["viewer", "action", "reason", "outcome", "error"]} /></section><section><h2>Observed viewers</h2><label>Find an observed viewer<input value={viewerQuery} onChange={event => setViewerQuery(event.target.value)} /></label><Table rows={s.viewers.filter(viewer => `${viewer.id} ${viewer.name}`.toLowerCase().includes(viewerQuery.toLowerCase()))} columns={["id", "name", "role", "last_seen"]} /></section>
  </>;
  if (panel === "Goals") return can("operate") && <ActionForm action="goal.adjust" fields={["target", "version", "value"]} button="Adjust or reset goal" run={run} busy={busy} />;
  if (panel === "Points & rewards") return <><p>Watchtime is an estimate from observed chat activity. Enable accrual in Maintenance settings.</p>{can("engage") && <ActionForm action="points.adjust" fields={["viewer", "amount", "reason"]} button="Adjust points" run={run} busy={busy} />}<Table rows={s.leaderboard} columns={["viewer", "balance"]} /><section><h2>Redemptions</h2>{s.redemptions.map(row => <article key={String(row.id)}><p>{text(row.viewer)} · {text(row.reward)} · {text(row.cost)} points · {text(row.status)}</p>{row.status === "pending" && can("engage") && <div className="actions"><button onClick={() => run("reward.complete", { target: row.id })}>Mark fulfilled</button><button className="secondary" onClick={() => run("reward.reject", { target: row.id })}>Reject and refund</button></div>}</article>)}</section></>;
  if (panel === "Polls & raffles") return <><p>Viewers use !vote &lt;option number&gt; and !enter in Kick chat. OBS sources only display results.</p><Table rows={s.activities} columns={["activity", "choice", "count"]} /></>;
  if (panel === "Widgets") return <p>Use independent revocable tokens for OBS Browser Sources. Player sources receive a separate acknowledgement credential. Revoke tokens in Maintenance.</p>;
  if (panel === "Analytics") return <><form onSubmit={async event => { event.preventDefault(); const values = new FormData(event.currentTarget); const params = new URLSearchParams({ view: "analytics", from: String(new Date(String(values.get("from"))).getTime()), to: String(new Date(String(values.get("to"))).getTime() + 86399999), ...(values.get("stream") ? { stream: String(values.get("stream")) } : {}) }); const response = await fetch(`/api/control?${params}`, { cache: "no-store" }); const result = await response.json(); if (response.ok) setAnalytics(result); else message(result.error); }}><h2>Observed history</h2><div className="fields"><label>From<input name="from" type="date" required /></label><label>To<input name="to" type="date" required /></label><label>Stream receipt ID (optional)<input name="stream" /></label></div><button>Load history</button><a className="button secondary" href="/api/control?view=analytics&format=csv">Download last 30 days CSV</a></form>{analytics && <section><p>{analytics.note}</p><p>Coverage: {JSON.stringify(analytics.coverage)}</p><div className="chart" aria-label="Observed daily metrics">{analytics.rows.slice(0, 60).map((row, i) => <div key={i}><span>{text(row.day)} · {text(row.metric)}</span><meter min={0} max={Math.max(1, ...analytics.rows.map(r => Number(r.value)))} value={Number(row.value)} /> <span>{text(row.value)}</span></div>)}</div><Table rows={analytics.rows} columns={["day", "metric", "value"]} /></section>}</>;
  if (panel === "Accounts" && owner) return <><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void run("account.invite", { role: form.get("role"), permissions: form.getAll("permissions") }); }}><h2>Invite an operator</h2><label>Role<select name="role"><option value="readonly">Read-only</option><option value="moderator">Moderator</option><option value="admin">Admin</option></select></label><p>Admin grants (owner powers cannot be delegated):</p><div className="actions">{["configure", "operate", "moderate", "media", "engage"].map(permission => <label key={permission}>{permission}<input name="permissions" type="checkbox" value={permission} /></label>)}</div><button disabled={busy}>Create one-day invitation</button></form><section><h2>Accounts</h2>{s.accounts?.map(account => <article key={String(account.id)}><h3>{text(account.username)}</h3><p>{text(account.role)} · {account.disabled ? "Disabled" : "Active"}</p><div className="actions">{account.role !== "owner" && <button className="secondary" onClick={() => run("account.disable", { id: account.id, disabled: !account.disabled })}>{account.disabled ? "Enable" : "Disable"}</button>}<button className="secondary" onClick={() => run("account.revoke", { id: account.id })}>Revoke sessions</button></div></article>)}</section></>;
  if (panel !== "Maintenance") return null;
  return <><section><h2>Diagnostics</h2><pre>{JSON.stringify(s.diagnostics, null, 2)}</pre>{owner && <button onClick={() => run("diagnostics.export")}>Generate redacted support data</button>}</section><section><h2>Delivery outcomes</h2><Table rows={s.jobs} columns={["id", "kind", "status", "error", "attempts"]} />{owner && s.jobs.filter(job => job.status === "uncertain").map(job => <article key={String(job.id)}><p>Inspect the provider before reconciling {text(job.id)}. This does not resend it.</p><button onClick={() => run("job.resolve", { id: job.id, result: "confirmed" })}>Provider confirms success</button><button className="secondary" onClick={() => run("job.resolve", { id: job.id, result: "failed" })}>Provider confirms failure</button></article>)}</section>
    {owner && <><section><h2>Source and API tokens</h2>{s.tokens?.map(token => <article key={String(token.id)}><p>{text(token.name)} · {text(token.kind)} · {text(token.scopes)}</p><button className="secondary" onClick={() => run("token.revoke", { id: token.id })}>Revoke</button></article>)}<form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); void run("token.create", { kind: "api", name: form.get("name"), scopes: form.getAll("scopes") }); }}><label>Token name<input name="name" required /></label><div className="actions">{["read", "configure", "operate", "moderate", "media", "engage"].map(scope => <label key={scope}>{scope}<input name="scopes" type="checkbox" value={scope} /></label>)}</div><button>Create API token</button></form></section><ActionForm action="privacy.export" fields={["viewer"]} button="Export viewer history" run={run} busy={busy} /><ActionForm action="privacy.erase" fields={["viewer"]} button="Erase retained viewer profile and chat" run={run} busy={busy} />
      <section><h2>Configuration portability</h2><button onClick={() => run("configuration.export")}>Export configuration</button><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); try { void run("configuration.import", { bundle: JSON.parse(String(form.get("bundle"))), mode: form.get("mode"), apply: form.get("apply") === "on" }); } catch { message("Invalid configuration JSON"); } }}><label>Versioned configuration JSON<textarea name="bundle" required rows={8} /></label><label>Mode<select name="mode"><option>merge</option><option>replace</option></select></label><label>Apply after reviewing the preview<input name="apply" type="checkbox" /></label><button>Validate / import</button></form></section><section><h2>Host maintenance</h2><p>Stop the application before backup, restore or owner recovery. Use the documented kekbot CLI with protected runtime files. Configuration exports exclude credentials, accounts and sessions.</p><a href="https://github.com/DangerMouseUK/kekbot/blob/main/docs/OPERATIONS.md" rel="noreferrer" target="_blank">Operator guide</a></section></>}
    <section><h2>Change password</h2><form onSubmit={async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/auth", { method: "POST", headers: { "Content-Type": "application/json", "X-CSRF-Token": auth.csrf ?? "" }, body: JSON.stringify({ action: "password", ...values }) }); if (response.ok) expired(); else message((await response.json()).error); }}><label>Current password<input name="currentPassword" type="password" autoComplete="current-password" required /></label><label>New password<input name="password" type="password" autoComplete="new-password" minLength={12} required /></label><button>Change password and revoke sessions</button></form></section>
  </>;
}
