import { z } from "zod";

const name = z.string().trim().min(1).max(80);
const text = z.string().max(500);
const snowflake = z.string().regex(/^\d{1,24}$/);
const chatRole = z.enum(["viewer", "subscriber", "vip", "moderator", "broadcaster"]);
const base = { name, enabled: z.boolean().default(true) };
export const widgetKinds = ["alerts", "chat", "player", "nowplaying", "queue", "eventfeed", "supporter", "goal", "multigoal", "status", "counter", "leaderboard", "poll", "raffle", "countdown", "shoutout", "socials", "activity"] as const;
export const configSchemas = {
  command: z.object({ ...base, trigger: z.string().regex(/^![a-z0-9_]{1,32}$/), aliases: z.array(z.string().regex(/^![a-z0-9_]{1,32}$/)).max(10).default([]), group: name.default("General"), responses: z.array(text.min(1)).min(1).max(20), roles: z.array(chatRole).max(5).default([]), cooldown: z.number().int().min(0).max(3600).default(10), userCooldown: z.number().int().min(0).max(86400).default(30), streamOnly: z.boolean().default(false), condition: z.enum(["always", "live", "offline"]).default("always"), counter: z.boolean().default(false) }),
  timer: z.object({ ...base, messages: z.array(text.min(1)).min(1).max(20), interval: z.number().int().min(60).max(86400), minMessages: z.number().int().min(0).max(10000).default(5), streamOnly: z.boolean().default(true), timezone: z.string().max(80).refine(value => { try { new Intl.DateTimeFormat("en", { timeZone: value }); return true; } catch { return false; } }).default("UTC"), quietStart: z.number().int().min(0).max(23).nullable().default(null), quietEnd: z.number().int().min(0).max(23).nullable().default(null) }),
  alert: z.object({ ...base, event: z.enum(["channel.followed", "channel.subscription.new", "channel.subscription.renewal", "channel.subscription.gifts", "manual", "goal", "media"]), template: text.min(1), duration: z.number().int().min(1).max(30).default(5), priority: z.number().int().min(0).max(10).default(0), image: z.string().max(100).nullable().default(null), sound: z.string().max(100).nullable().default(null), volume: z.number().min(0).max(1).default(0.5), animation: z.enum(["fade", "slide", "none"]).default("fade") }),
  widget: z.object({ ...base, type: z.enum(widgetKinds), theme: z.enum(["mint", "midnight", "paper"]).default("mint"), width: z.number().int().min(200).max(3840).default(800), height: z.number().int().min(100).max(2160).default(400), limit: z.number().int().min(1).max(50).default(10), target: z.string().max(100).default(""), text: text.default(""), endsAt: z.number().int().nonnegative().nullable().default(null), reducedMotion: z.boolean().default(false) }),
  rule: z.object({ ...base, type: z.enum(["link", "phrase", "repetition", "caps", "burst"]), patterns: z.array(z.string().min(1).max(120)).max(100).default([]), allowedDomains: z.array(z.string().regex(/^[a-z0-9.-]{1,253}$/)).max(100).default([]), threshold: z.number().int().min(1).max(100).default(5), windowSeconds: z.number().int().min(1).max(600).default(30), trustedRoles: z.array(chatRole).max(5).default(["moderator", "broadcaster"]), action: z.enum(["warn", "delete", "timeout", "ban"]).default("warn"), duration: z.number().int().min(1).max(10080).default(10), startsAt: z.number().int().nonnegative().nullable().default(null), endsAt: z.number().int().nonnegative().nullable().default(null), escalation: z.boolean().default(false) }),
  goal: z.object({ ...base, metric: z.enum(["manual", "follow", "subscription", "points", "media"]), target: z.number().int().min(1).max(1000000000), value: z.number().int().min(0).max(1000000000).default(0), completed: z.boolean().default(false) }),
  reward: z.object({ ...base, cost: z.number().int().min(1).max(100000000), description: text.default(""), fulfillment: z.enum(["manual", "alert"]).default("manual") }),
  poll: z.object({ ...base, options: z.array(name).min(2).max(10), status: z.enum(["open", "closed"]).default("open"), endsAt: z.number().int().positive(), allowChange: z.boolean().default(false) }),
  raffle: z.object({ ...base, status: z.enum(["open", "closed", "drawn"]).default("open"), endsAt: z.number().int().positive(), roles: z.array(chatRole).max(5).default([]), minPoints: z.number().int().min(0).default(0), winners: z.array(z.string().max(100)).max(100).default([]) }),
  note: z.object({ ...base, viewer: snowflake, text: z.string().min(1).max(2000) }),
  guild: z.object({ ...base, guildId: snowflake, channelId: snowflake, events: z.array(z.enum(["live", "offline", "alert", "media", "goal", "moderation", "engagement"])).max(7).default([]), roles: z.array(z.object({ id: snowflake, permission: z.enum(["operate", "moderate", "media", "engage"]) })).max(30).default([]), users: z.array(z.object({ id: snowflake, permission: z.enum(["operate", "moderate", "media", "engage"]) })).max(30).default([]) }),
  settings: z.object({ name: name.default("KekBot"), rules: text.default(""), discord: text.default(""), socials: text.default(""), mediaEnabled: z.boolean().default(false), autoApprove: z.boolean().default(false), maxDuration: z.number().int().min(1).max(43200).default(600), capacity: z.number().int().min(1).max(500).default(50), perUser: z.number().int().min(1).max(50).default(3), requestCooldown: z.number().int().min(0).max(3600).default(30), allowDuplicates: z.boolean().default(false), blockedUploaders: z.array(name).max(100).default([]), blockedTitles: z.array(name).max(100).default([]), moderationPaused: z.boolean().default(false), timersPaused: z.boolean().default(false), pointsEnabled: z.boolean().default(false), pointsAmount: z.number().int().min(1).max(1000).default(10), pointsInterval: z.number().int().min(60).max(3600).default(300), activeWindow: z.number().int().min(60).max(3600).default(300), chatDays: z.number().int().min(0).max(30).default(7), receiptDays: z.number().int().min(2).max(90).default(30), summaryDays: z.number().int().min(1).max(3650).default(90), auditDays: z.number().int().min(30).max(3650).default(365) })
} as const;
export type Kind = keyof typeof configSchemas;
export type ConfigDocument = { id: string; kind: Kind; data: Record<string, unknown>; version: number; updatedAt: number };
export type Settings = z.infer<typeof configSchemas.settings>;
export const defaults = configSchemas.settings.parse({});
